project:
  type: website
  output-dir: docs

website:
  title: "Placeholders!"
  navbar:
    left:
      - href: index.qmd #to hyperlink the file
        text: Visualisations #to change the name of the tab
      - href: about.qmd
        text: Write Up

format:
  html:
    page-layout: full
    theme: cyborg
    css: styles.css
    toc: true

editor: visual

