project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "Meet Dawn Cheung"
  navbar:
    search: true
    left:
      - text: Home #to change the name of the tab {Visualisations}
        href: index.qmd #to hyperlink the file
      - text: The Digital Divideâ€” and Why it Matters
        menu: 
          - text: Data Story            
            href: TDD-Visualisations.qmd
          - text: Sources and Write Up
            href: TDD-Sources-Write-Up.qmd
          - text: Scrapped Content
            href: TDD-Scrapped.qmd
      - text: Viral Videos
        href: videos_proj
      - text: Great Graphics
        href: graphics_proj
      - text: Leadership / Legendary Projects
        href: misc_proj
      - text: CV
        href: Resume.qmd

  sidebar: 
    - title: Work
      contents:
        - talks.qmd
        - work_proj/index.qmd
    - title: Play
      contents:
        - play_start.qmd
        - play_proj/index.qmd
        

format:
  html:
    page-layout: full
    theme: cyborg
    css: styles.css
    toc: true

editor: visual

